//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HatunsolDAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class SG_Articulo
    {
        public SG_Articulo()
        {
            this.SG_Establecimiento_Articulo = new HashSet<SG_Establecimiento_Articulo>();
            this.SG_GuiaDespacho_Articulo = new HashSet<SG_GuiaDespacho_Articulo>();
            this.SG_GuiaRemision_Articulo = new HashSet<SG_GuiaRemision_Articulo>();
            this.SG_Obra_Material = new HashSet<SG_Obra_Material>();
            this.SG_OrdenCompra_Articulo = new HashSet<SG_OrdenCompra_Articulo>();
            this.SG_PresupuestoMaterial_Articulo = new HashSet<SG_PresupuestoMaterial_Articulo>();
            this.SG_Proveedor_Articulo = new HashSet<SG_Proveedor_Articulo>();
            this.SG_Promocion_Articulo = new HashSet<SG_Promocion_Articulo>();
        }
    
        public int IdArticulo { get; set; }
        public int IdCategoria { get; set; }
        public Nullable<int> IdMarca { get; set; }
        public string Nombre { get; set; }
        public int UnidadMedida { get; set; }
    
        public virtual SG_Categoria SG_Categoria { get; set; }
        public virtual SG_Marca SG_Marca { get; set; }
        public virtual ICollection<SG_Establecimiento_Articulo> SG_Establecimiento_Articulo { get; set; }
        public virtual ICollection<SG_GuiaDespacho_Articulo> SG_GuiaDespacho_Articulo { get; set; }
        public virtual ICollection<SG_GuiaRemision_Articulo> SG_GuiaRemision_Articulo { get; set; }
        public virtual ICollection<SG_Obra_Material> SG_Obra_Material { get; set; }
        public virtual ICollection<SG_OrdenCompra_Articulo> SG_OrdenCompra_Articulo { get; set; }
        public virtual ICollection<SG_PresupuestoMaterial_Articulo> SG_PresupuestoMaterial_Articulo { get; set; }
        public virtual ICollection<SG_Proveedor_Articulo> SG_Proveedor_Articulo { get; set; }
        public virtual ICollection<SG_Promocion_Articulo> SG_Promocion_Articulo { get; set; }
    }
}
