//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HatunsolDAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class SG_Carta_Aprobacion
    {
        public int IdCartaAprobacion { get; set; }
        public Nullable<decimal> EfectivoApro { get; set; }
        public Nullable<decimal> MaterialApro { get; set; }
        public Nullable<int> FrecuenciaPago { get; set; }
        public Nullable<System.DateTime> FechaAprobacion { get; set; }
        public Nullable<System.DateTime> FechaVencimiento { get; set; }
        public Nullable<int> NroCuotas { get; set; }
        public Nullable<decimal> MontoCuotas { get; set; }
        public string Observacion { get; set; }
        public Nullable<int> IdSolicitud { get; set; }
    
        public virtual SG_Solicitud SG_Solicitud { get; set; }
    }
}
