//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HatunsolDAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class SG_Dominio
    {
        public SG_Dominio()
        {
            this.SG_Parametro = new HashSet<SG_Parametro>();
        }
    
        public int DominioId { get; set; }
        public string Nombre { get; set; }
    
        public virtual ICollection<SG_Parametro> SG_Parametro { get; set; }
    }
}
