//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HatunsolDAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class SG_Establecimiento
    {
        public SG_Establecimiento()
        {
            this.SG_Establecimiento_Articulo = new HashSet<SG_Establecimiento_Articulo>();
            this.SG_OrdenCompra = new HashSet<SG_OrdenCompra>();
            this.SG_PresupuestoMaterial = new HashSet<SG_PresupuestoMaterial>();
            this.SG_Solicitud = new HashSet<SG_Solicitud>();
            this.SG_GuiaDespacho = new HashSet<SG_GuiaDespacho>();
            this.SG_Promocion = new HashSet<SG_Promocion>();
        }
    
        public int IdEstablecimiento { get; set; }
        public string RazonSocial { get; set; }
        public string NombreComercial { get; set; }
        public Nullable<int> TipoEstablecimiento { get; set; }
        public string RUC { get; set; }
        public string Direccion { get; set; }
        public string Referencia { get; set; }
        public string NumeroCuenta { get; set; }
        public Nullable<int> TipoCuenta { get; set; }
        public string DuenoCuenta { get; set; }
        public string TipoDocumentoCuenta { get; set; }
        public string Telefono { get; set; }
        public string CCI { get; set; }
        public string Email { get; set; }
        public Nullable<int> Estado { get; set; }
        public string Contacto { get; set; }
        public string DNIContacto { get; set; }
        public string Latitud { get; set; }
        public string Longitud { get; set; }
    
        public virtual ICollection<SG_Establecimiento_Articulo> SG_Establecimiento_Articulo { get; set; }
        public virtual ICollection<SG_OrdenCompra> SG_OrdenCompra { get; set; }
        public virtual ICollection<SG_PresupuestoMaterial> SG_PresupuestoMaterial { get; set; }
        public virtual ICollection<SG_Solicitud> SG_Solicitud { get; set; }
        public virtual ICollection<SG_GuiaDespacho> SG_GuiaDespacho { get; set; }
        public virtual ICollection<SG_Promocion> SG_Promocion { get; set; }
    }
}
