//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HatunsolDAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class SG_GuiaRemision
    {
        public SG_GuiaRemision()
        {
            this.SG_GuiaRemision_Articulo = new HashSet<SG_GuiaRemision_Articulo>();
        }
    
        public int IdGuiaRemision { get; set; }
        public int IdOrdenCompra { get; set; }
        public System.DateTime Fecha { get; set; }
        public string DireccionOrigen { get; set; }
        public string DireccionDestino { get; set; }
        public int ModalidadPago { get; set; }
        public Nullable<System.DateTime> FechaTraslado { get; set; }
    
        public virtual ICollection<SG_GuiaRemision_Articulo> SG_GuiaRemision_Articulo { get; set; }
        public virtual SG_OrdenCompra SG_OrdenCompra { get; set; }
    }
}
