//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HatunsolDAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class SG_Ingeniero
    {
        public SG_Ingeniero()
        {
            this.SG_InformeVisita = new HashSet<SG_InformeVisita>();
        }
    
        public int IdIngeniero { get; set; }
        public string Nombre { get; set; }
        public string ApePaterno { get; set; }
        public string ApeMaterno { get; set; }
        public string DNI { get; set; }
        public string CIP { get; set; }
        public string CodUbigeo { get; set; }
    
        public virtual ICollection<SG_InformeVisita> SG_InformeVisita { get; set; }
    }
}
