//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HatunsolDAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class SG_InformeVisita
    {
        public int IdInformeVisita { get; set; }
        public int IdSolicitud { get; set; }
        public int IdIngeniero { get; set; }
        public string Direccion { get; set; }
        public string Telefonos { get; set; }
        public int Presente { get; set; }
        public System.DateTime Fecha { get; set; }
        public Nullable<System.TimeSpan> HoraLlegada { get; set; }
        public Nullable<System.TimeSpan> HoraInicio { get; set; }
        public Nullable<System.TimeSpan> HoraFinal { get; set; }
        public Nullable<int> CantFotos { get; set; }
        public Nullable<System.TimeSpan> Duracion { get; set; }
        public string Descripcion { get; set; }
        public string Observacion { get; set; }
    
        public virtual SG_Ingeniero SG_Ingeniero { get; set; }
        public virtual SG_Solicitud SG_Solicitud { get; set; }
    }
}
