//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HatunsolDAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class SG_Maestro_Obra
    {
        public int IdMaestro { get; set; }
        public int IdObra { get; set; }
        public decimal PrecioDia { get; set; }
        public decimal AreaDia { get; set; }
    
        public virtual SG_Maestro SG_Maestro { get; set; }
        public virtual SG_Obra SG_Obra { get; set; }
    }
}
