//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HatunsolDAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class SG_Marca
    {
        public SG_Marca()
        {
            this.SG_Articulo = new HashSet<SG_Articulo>();
        }
    
        public int IdMarca { get; set; }
        public string Nombre { get; set; }
    
        public virtual ICollection<SG_Articulo> SG_Articulo { get; set; }
    }
}
