//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HatunsolDAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class SG_Obra
    {
        public SG_Obra()
        {
            this.SG_Maestro_Obra = new HashSet<SG_Maestro_Obra>();
            this.SG_Obra_Material = new HashSet<SG_Obra_Material>();
            this.SG_PresupuestoMo = new HashSet<SG_PresupuestoMo>();
            this.SG_PresupuestoMaterial = new HashSet<SG_PresupuestoMaterial>();
        }
    
        public int IdObra { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> UnidadMedidaId { get; set; }
        public string Foto { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<SG_Maestro_Obra> SG_Maestro_Obra { get; set; }
        public virtual ICollection<SG_Obra_Material> SG_Obra_Material { get; set; }
        public virtual ICollection<SG_PresupuestoMo> SG_PresupuestoMo { get; set; }
        public virtual ICollection<SG_PresupuestoMaterial> SG_PresupuestoMaterial { get; set; }
    }
}
