//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HatunsolDAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class SG_Option
    {
        public SG_Option()
        {
            this.SG_Rol_Option = new HashSet<SG_Rol_Option>();
        }
    
        public int IdOption { get; set; }
        public string Nombre { get; set; }
        public string Action { get; set; }
        public string Controller { get; set; }
        public int Orden { get; set; }
    
        public virtual ICollection<SG_Rol_Option> SG_Rol_Option { get; set; }
    }
}
