//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HatunsolDAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class SG_PresupuestoMo_Maestro
    {
        public int IdPresupuestoMo { get; set; }
        public int IdMaestro { get; set; }
        public int Dias { get; set; }
        public decimal SubTotal { get; set; }
    
        public virtual SG_Maestro SG_Maestro { get; set; }
        public virtual SG_PresupuestoMo SG_PresupuestoMo { get; set; }
    }
}
