//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HatunsolDAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class SG_Promocion_Articulo
    {
        public int IdPromocion { get; set; }
        public int IdArticulo { get; set; }
        public decimal PrecioNuevo { get; set; }
    
        public virtual SG_Articulo SG_Articulo { get; set; }
        public virtual SG_Promocion SG_Promocion { get; set; }
    }
}
