//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HatunsolDAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class SG_Proveedor
    {
        public SG_Proveedor()
        {
            this.SG_OrdenCompra = new HashSet<SG_OrdenCompra>();
            this.SG_Proveedor_Articulo = new HashSet<SG_Proveedor_Articulo>();
        }
    
        public int IdProveedor { get; set; }
        public string RazonSocial { get; set; }
        public string RUC { get; set; }
        public Nullable<int> IdCategoria { get; set; }
        public string Direccion { get; set; }
        public string Referencia { get; set; }
        public string Contacto { get; set; }
        public string Email { get; set; }
        public Nullable<int> Estado { get; set; }
    
        public virtual SG_Categoria SG_Categoria { get; set; }
        public virtual ICollection<SG_OrdenCompra> SG_OrdenCompra { get; set; }
        public virtual ICollection<SG_Proveedor_Articulo> SG_Proveedor_Articulo { get; set; }
    }
}
