//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HatunsolDAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class SG_PresupuestoMaterial
    {
        public SG_PresupuestoMaterial()
        {
            this.SG_PresupuestoMaterial_Articulo = new HashSet<SG_PresupuestoMaterial_Articulo>();
        }
    
        public int IdPresupuestoMaterial { get; set; }
        public int IdEstablecimiento { get; set; }
        public int IdPersona { get; set; }
        public int IdObra { get; set; }
        public System.DateTime Fecha { get; set; }
        public string DireccionOrigen { get; set; }
        public string DireccionDestino { get; set; }
        public decimal SubTotal { get; set; }
        public decimal Area { get; set; }
        public decimal IGV { get; set; }
        public decimal Total { get; set; }
        public Nullable<int> EstadoDespacho { get; set; }
    
        public virtual SG_Establecimiento SG_Establecimiento { get; set; }
        public virtual SG_Obra SG_Obra { get; set; }
        public virtual ICollection<SG_PresupuestoMaterial_Articulo> SG_PresupuestoMaterial_Articulo { get; set; }
        public virtual SG_Persona SG_Persona { get; set; }
    }
}
