//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HatunsolDAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class SG_Proveedor_Articulo
    {
        public int IdProveedor { get; set; }
        public int IdArticulo { get; set; }
        public decimal Costo { get; set; }
    
        public virtual SG_Articulo SG_Articulo { get; set; }
        public virtual SG_Proveedor SG_Proveedor { get; set; }
    }
}
