//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HatunsolDAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class SG_Parametro
    {
        public int DominioId { get; set; }
        public int ParametroId { get; set; }
        public string NombreCorto { get; set; }
        public string NombreLargo { get; set; }
        public bool Estado { get; set; }
    
        public virtual SG_Dominio SG_Dominio { get; set; }
    }
}
