//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HatunsolDAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class SG_Rol
    {
        public SG_Rol()
        {
            this.SG_Rol_Option = new HashSet<SG_Rol_Option>();
            this.SG_User = new HashSet<SG_User>();
        }
    
        public int RolId { get; set; }
        public string RolDes { get; set; }
    
        public virtual ICollection<SG_Rol_Option> SG_Rol_Option { get; set; }
        public virtual ICollection<SG_User> SG_User { get; set; }
    }
}
