//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HatunsolDAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class SG_Rol_Option
    {
        public int RolId { get; set; }
        public int IdOption { get; set; }
        public Nullable<int> Orden { get; set; }
    
        public virtual SG_Option SG_Option { get; set; }
        public virtual SG_Rol SG_Rol { get; set; }
    }
}
