//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HatunsolDAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class SG_Solicitud
    {
        public SG_Solicitud()
        {
            this.SG_Carta_Aprobacion = new HashSet<SG_Carta_Aprobacion>();
            this.SG_InformeVisita = new HashSet<SG_InformeVisita>();
            this.SG_Solicitud_Persona = new HashSet<SG_Solicitud_Persona>();
        }
    
        public int IdSolicitud { get; set; }
        public decimal MontoEfectivoProp { get; set; }
        public decimal MontoMaterialProp { get; set; }
        public System.DateTime FechaSolicitud { get; set; }
        public string Obra { get; set; }
        public Nullable<int> IdEstablecimiento { get; set; }
        public Nullable<int> EstadoDespacho { get; set; }
    
        public virtual ICollection<SG_Carta_Aprobacion> SG_Carta_Aprobacion { get; set; }
        public virtual SG_Establecimiento SG_Establecimiento { get; set; }
        public virtual ICollection<SG_InformeVisita> SG_InformeVisita { get; set; }
        public virtual ICollection<SG_Solicitud_Persona> SG_Solicitud_Persona { get; set; }
    }
}
