//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HatunsolDAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class SG_Solicitud_Persona
    {
        public int IdPersona { get; set; }
        public int IdSolicitud { get; set; }
        public Nullable<int> TipoPersona { get; set; }
        public Nullable<int> ResultadoFiltro { get; set; }
    
        public virtual SG_Solicitud SG_Solicitud { get; set; }
        public virtual SG_Persona SG_Persona { get; set; }
    }
}
