//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HatunsolDAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class SG_Ubigeo
    {
        public SG_Ubigeo()
        {
            this.SG_Persona = new HashSet<SG_Persona>();
        }
    
        public string CodUbigeo { get; set; }
        public string CodDpto { get; set; }
        public string CodProv { get; set; }
        public string CodDist { get; set; }
        public string Nombre { get; set; }
        public string NombreCorto { get; set; }
    
        public virtual ICollection<SG_Persona> SG_Persona { get; set; }
    }
}
